# Architecture tests - Symlinks, runtime directories, config structure
#
# Tests: Pre-generated configs, current-theme symlink, app symlinks, file accessibility
#
{ pkgs
, vogix16Themes
, home-manager
, self
,
}:

let
  testLib = import ./lib.nix {
    inherit
      pkgs
      home-manager
      self
      vogix16Themes
      ;
  };
in
testLib.mkTest "architecture" ''
  print("=== Test: Nix Pre-Generated Theme-Variant Configs ===")

  # Verify theme-variant directories exist in ~/.local/share/vogix/themes/
  # Note: aikido uses 'night' for dark polarity and 'day' for light polarity
  machine.succeed(f"su - vogix -c 'test -d {vogix_themes}/aikido-night'")
  print(f"✓ aikido-night (dark) theme-variant directory exists in {vogix_themes}/")

  machine.succeed(f"su - vogix -c 'test -d {vogix_themes}/aikido-day'")
  print(f"✓ aikido-day (light) theme-variant directory exists in {vogix_themes}/")

  # Check that configs are pre-generated with actual colors (not {{baseXX}})
  aikido_night_config = machine.succeed(f"su - vogix -c 'cat {vogix_themes}/aikido-night/alacritty/alacritty.toml 2>/dev/null || echo NOTFOUND'")
  if "NOTFOUND" not in aikido_night_config:
      print("✓ aikido-night alacritty config exists")
      assert "{{base" not in aikido_night_config, "Config contains unprocessed template placeholders!"
      assert "#" in aikido_night_config, "Config missing hex colors!"
      print("✓ aikido-night config has actual colors (no {{baseXX}} placeholders)")

  aikido_day_config = machine.succeed(f"su - vogix -c 'cat {vogix_themes}/aikido-day/alacritty/alacritty.toml 2>/dev/null || echo NOTFOUND'")
  if "NOTFOUND" not in aikido_day_config:
      print("✓ aikido-day alacritty config exists")
      assert "{{base" not in aikido_day_config, "Config contains unprocessed template placeholders!"
      assert aikido_night_config != aikido_day_config, "Night and day configs are identical!"
      print("✓ aikido-day config differs from aikido-night (variants work)")

  print("\n=== Test: Current-Theme Symlink Exists ===")
  # current-theme symlink is in ~/.local/state/vogix/, not themes dir
  machine.succeed(f"su - vogix -c 'test -L {current_theme}'")
  print(f"✓ 'current-theme' symlink exists at {current_theme}")

  current_target = machine.succeed(f"su - vogix -c 'readlink {current_theme}'")
  print(f"✓ 'current-theme' points to: {current_target.strip()}")
  assert "aikido" in current_target.lower(), "current-theme symlink doesn't point to default aikido theme"
  # aikido uses 'night' as its dark polarity variant name
  assert "night" in current_target.lower(), "current-theme symlink doesn't point to night (dark) variant"

  print("\n=== Test: User Config Contains App Reload Methods ===")
  # User config is at ~/.local/state/vogix/config.toml (generated by home-manager)
  config_content = machine.succeed(f"su - vogix -c 'cat {vogix_config}/config.toml'")
  print("Config content (first 500 chars):")
  print(config_content[:500])

  app_sections = re.findall(r'\[apps\.([^\]]+)\]', config_content)
  assert len(app_sections) > 0, "Config has no [apps.*] sections!"
  print(f"✓ Config contains {len(app_sections)} app sections")

  # config_path must contain FULL paths (e.g., /home/vogix/.config/alacritty/alacritty.toml)
  assert "config_path" in config_content, "Config missing config_path field!"
  assert "reload_method" in config_content, "Config missing reload_method field!"
  # Verify paths are full paths, not just filenames
  assert "/home/vogix/.config/" in config_content, "config_path should contain full paths, not just filenames!"
  print("✓ Config has required config_path (full paths) and reload_method fields")

  print("\n=== Test: ~/.config/vogix Does NOT Exist ===")
  vogix_user_config_check = machine.execute("su - vogix -c 'test -d ~/.config/vogix && echo EXISTS || echo NOTEXIST'")
  if "EXISTS" in vogix_user_config_check[1]:
      raise AssertionError("FAILED: ~/.config/vogix exists! Config should be in ~/.local/state/vogix/")
  print("✓ ~/.config/vogix does NOT exist (correct - config in ~/.local/state/vogix/)")

  print("\n=== Test: App Config Symlinks Point Through Current-Theme ===")
  # In the new architecture, app config symlinks are created by home-manager activation
  # They point to ~/.local/state/vogix/current-theme/{app}/{config}

  # Test alacritty config symlink
  alacritty_config = "/home/vogix/.config/alacritty/alacritty.toml"
  link_check = machine.execute(f"su - vogix -c 'test -L {alacritty_config} && echo SYMLINK || echo NOTLINK'")
  if "SYMLINK" in link_check[1]:
      target = machine.succeed(f"su - vogix -c 'readlink {alacritty_config}'").strip()
      print(f"  alacritty symlink target: {target}")
      assert "current-theme" in target, f"alacritty symlink should point through current-theme! Got: {target}"
      print("  ✓ alacritty config symlink points through current-theme")
  else:
      print("  ⚠ alacritty config is not a symlink (may not be enabled)")

  # Test btop config symlink
  btop_config = "/home/vogix/.config/btop/btop.conf"
  link_check = machine.execute(f"su - vogix -c 'test -L {btop_config} && echo SYMLINK || echo NOTLINK'")
  if "SYMLINK" in link_check[1]:
      target = machine.succeed(f"su - vogix -c 'readlink {btop_config}'").strip()
      print(f"  btop symlink target: {target}")
      assert "current-theme" in target, f"btop symlink should point through current-theme! Got: {target}"
      print("  ✓ btop config symlink points through current-theme")
  else:
      print("  ⚠ btop config is not a symlink (may not be enabled)")

  print("\n=== Test: Config Files Accessible Through Current-Theme ===")
  # Test that configs are accessible through the current-theme symlink
  alacritty_via_current = machine.execute(f"su - vogix -c 'cat {current_theme}/alacritty/alacritty.toml 2>/dev/null'")
  if alacritty_via_current[0] == 0:
      print("  ✓ alacritty config accessible through current-theme")
  else:
      print("  ⚠ alacritty config not accessible through current-theme")

  btop_via_current = machine.execute(f"su - vogix -c 'cat {current_theme}/btop/btop.conf 2>/dev/null'")
  if btop_via_current[0] == 0:
      print("  ✓ btop config accessible through current-theme")
  else:
      print("  ⚠ btop config not accessible through current-theme")

  print("\n✓ Architecture verified!")

  print("\n" + "="*60)
  print("ARCHITECTURE TESTS PASSED!")
  print("="*60)
''
