# Template architecture tests - Verify runtime template rendering
#
# Tests: Templates setup, theme sources, cache rendering, color substitution
#
{ pkgs
, vogix16Themes
, home-manager
, self
,
}:

let
  testLib = import ./lib.nix {
    inherit
      pkgs
      home-manager
      self
      vogix16Themes
      ;
  };
in
testLib.mkTest "templates" ''
  print("=== Test: User Config Contains Template References ===")

  # User config is at ~/.local/state/vogix/config.toml (generated by home-manager)
  config_content = machine.succeed(f"su - vogix -c 'cat {vogix_config}/config.toml'")

  # Check templates section exists
  assert "[templates]" in config_content, "config.toml missing [templates] section"
  assert "path = " in config_content, "config.toml missing templates.path"
  assert "hash = " in config_content, "config.toml missing templates.hash"
  print("  > [templates] section present with path and hash")

  # Extract templates path from config
  templates_path_match = re.search(r'path = "([^"]+)"', config_content)
  assert templates_path_match, "Could not extract templates path from config"
  templates_path = templates_path_match.group(1)
  assert "/nix/store" in templates_path, f"Templates should be in /nix/store, got: {templates_path}"
  print(f"  > Templates path: {templates_path}")

  # Check theme_sources section exists
  assert "[theme_sources]" in config_content, "config.toml missing [theme_sources] section"
  assert "vogix16 = " in config_content, "config.toml missing theme_sources.vogix16"
  assert "base16 = " in config_content, "config.toml missing theme_sources.base16"
  assert "base24 = " in config_content, "config.toml missing theme_sources.base24"
  assert "ansi16 = " in config_content, "config.toml missing theme_sources.ansi16"
  print("  > [theme_sources] section present with all schemes")

  print("  User config verified")

  print("\n=== Test: Template Files Exist in Nix Store ===")

  # Check template directories exist for all schemes
  for scheme in ["vogix16", "base16", "base24", "ansi16"]:
      machine.succeed(f"su - vogix -c 'test -d {templates_path}/{scheme}'")
      print(f"  > {scheme} templates directory exists")

  # Check alacritty template exists for vogix16
  machine.succeed(f"su - vogix -c 'test -f {templates_path}/vogix16/alacritty.toml.vogix'")
  print("  > alacritty.toml.vogix exists")

  # Check btop template exists
  machine.succeed(f"su - vogix -c 'test -f {templates_path}/vogix16/btop.theme.vogix'")
  print("  > btop.theme.vogix exists")

  # Check console template exists
  machine.succeed(f"su - vogix -c 'test -f {templates_path}/vogix16/console.palette.vogix'")
  print("  > console.palette.vogix exists")

  print("  All template files verified")

  print("\n=== Test: Template Content Has Tera Variables ===")

  # Read alacritty template and verify it has Tera variables
  alacritty_template = machine.succeed(f"su - vogix -c 'cat {templates_path}/vogix16/alacritty.toml.vogix'")

  assert "{{ colors." in alacritty_template, "Template should contain Tera color variables"
  assert "{{ colors.background }}" in alacritty_template, "Template should reference colors.background"
  assert "{{ colors.foreground_text }}" in alacritty_template, "Template should reference colors.foreground_text"
  print("  > alacritty template contains Tera variables")

  print("  Template content verified")

  print("\n=== Test: Theme Sources in Nix Store ===")

  # Extract vogix16 source path from config
  vogix16_match = re.search(r'vogix16 = "([^"]+)"', config_content)
  assert vogix16_match, "Could not extract vogix16 path from config"
  vogix16_path = vogix16_match.group(1)
  assert "/nix/store" in vogix16_path, f"vogix16 source should be in /nix/store, got: {vogix16_path}"
  print(f"  > vogix16 source: {vogix16_path}")

  # Check vogix16 theme files are accessible
  aikido_night = machine.succeed(f"su - vogix -c 'cat {vogix16_path}/aikido/night.toml'")
  assert "polarity" in aikido_night, "Theme file should have polarity"
  assert "[colors]" in aikido_night, "Theme file should have [colors] section"
  assert "base00" in aikido_night, "Theme file should have base00"
  print("  > aikido/night.toml readable with correct structure")

  print("  Theme source files verified")

  print("\n=== Test: Pre-Generated Configs in Theme Packages ===")

  # In the new architecture, configs are pre-generated in ~/.local/share/vogix/themes/
  # Check aikido-night has pre-generated alacritty config
  alacritty_config = machine.succeed(f"su - vogix -c 'cat {vogix_themes}/aikido-night/alacritty/alacritty.toml'")
  assert "{{ colors." not in alacritty_config, "Config should be pre-rendered, not have Tera variables!"
  assert "#" in alacritty_config, "Config should have actual hex colors"
  print("  > aikido-night/alacritty/alacritty.toml is pre-rendered")

  # Check current-theme symlink points to themes dir
  current_target = machine.succeed(f"su - vogix -c 'readlink {current_theme}'").strip()
  assert "aikido" in current_target, "current-theme should point to aikido"
  print(f"  > current-theme -> {current_target}")

  # Verify configs accessible through current-theme
  current_alacritty = machine.succeed(f"su - vogix -c 'cat {current_theme}/alacritty/alacritty.toml'")
  assert "#" in current_alacritty, "Config through current-theme should have colors"
  print("  > Config accessible through current-theme symlink")

  print("  Pre-generated configs verified")

  print("\n" + "="*60)
  print("TEMPLATE ARCHITECTURE TESTS PASSED!")
  print("="*60)
''
