//! Theme module - theme discovery, types, loading, and query functions.
//!
//! This module provides:
//! - `ThemeInfo` and `VariantInfo` types for representing themes
//! - Theme discovery from runtime config manifest
//! - Theme color loading from various scheme formats
//! - Query functions for filtering and finding themes
//! - Theme variant path verification

mod discovery;
pub mod loader;
mod query;
pub mod types;

use crate::errors::{Result, VogixError};
use std::path::PathBuf;

// Re-export public API
pub use discovery::discover_themes;
pub use loader::load_theme_colors;
pub use query::{filter_by_scheme, get_theme};

/// Verify that a theme-variant directory exists in ~/.local/share/vogix/themes/
///
/// All theme configs are pre-generated by home-manager at build time.
/// This function verifies the expected directory exists before attempting to use it.
pub fn verify_theme_variant_exists(theme: &str, variant: &str) -> Result<PathBuf> {
    let themes_dir = crate::config::Config::themes_dir();
    let theme_path = themes_dir.join(format!("{}-{}", theme, variant));

    if !theme_path.exists() {
        return Err(VogixError::ThemeNotFound(format!(
            "theme variant {}-{} not found at {}",
            theme,
            variant,
            theme_path.display()
        )));
    }

    Ok(theme_path)
}
