use crate::errors::{Result, VogixError};
use std::path::PathBuf;

/// Theme generator - simplified to only verify theme-variant directories exist
/// All actual config generation happens at build time via Nix
pub struct ThemeGenerator;

impl ThemeGenerator {
    pub fn new() -> Self {
        ThemeGenerator
    }

    /// Verify that a theme-variant directory exists
    /// Nix pre-generates all theme-variant configs, we just check they exist
    pub fn verify_theme_variant_exists(&self, theme: &str, variant: &str) -> Result<PathBuf> {
        let runtime_dir = crate::config::Config::runtime_dir()?;
        let themes_dir = runtime_dir.join("themes");

        let theme_path = themes_dir.join(format!("{}-{}", theme, variant));

        if !theme_path.exists() {
            return Err(VogixError::ThemeNotFound(format!(
                "Theme variant {}-{} not found at {}. Available theme-variants are pre-generated by Nix.",
                theme,
                variant,
                theme_path.display()
            )));
        }

        Ok(theme_path)
    }
}

impl Default for ThemeGenerator {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generator_creation() {
        let generator = ThemeGenerator::new();
        // Just verify it can be created
        assert_eq!(std::mem::size_of_val(&generator), 0); // Zero-sized type
    }
}
