use crate::errors::{Result, VogixError};
use serde::{Deserialize, Serialize};
use std::fs;

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct Theme {
    pub name: String,
    pub description: Option<String>,
    pub author: Option<String>,
    pub dark: ColorPalette,
    pub light: ColorPalette,
}

#[derive(Debug, Serialize, Deserialize, Clone)]
pub struct ColorPalette {
    pub base00: String,
    pub base01: String,
    pub base02: String,
    pub base03: String,
    pub base04: String,
    pub base05: String,
    pub base06: String,
    pub base07: String,
    pub base08: String, // Error/Danger
    pub base09: String, // Warning/Caution
    #[serde(rename = "base0A")]
    pub base0a: String, // Notice/Attention
    #[serde(rename = "base0B")]
    pub base0b: String, // Success/Confirmed
    #[serde(rename = "base0C")]
    pub base0c: String, // Active/Current
    #[serde(rename = "base0D")]
    pub base0d: String, // Information/Interactive
    #[serde(rename = "base0E")]
    pub base0e: String, // Focus/Highlight
    #[serde(rename = "base0F")]
    pub base0f: String, // Special States
}

impl Theme {
    /// Discover all available themes by reading the themes.toml manifest
    /// generated by home-manager
    pub fn discover_themes() -> Result<Vec<String>> {
        let mut themes = Vec::new();

        // Read manifest.toml from runtime directory (/run/user/UID/vogix16/manifest.toml)
        let runtime_dir = crate::config::Config::runtime_dir()?;
        let manifest_path = runtime_dir.join("manifest.toml");

        if !manifest_path.exists() {
            return Err(VogixError::ConfigNotFound(manifest_path));
        }

        let content = fs::read_to_string(&manifest_path)
            .map_err(|_| VogixError::ConfigNotFound(manifest_path.clone()))?;

        // Parse TOML to extract theme names
        let manifest: toml::Value = content.parse().map_err(|e| {
            VogixError::InvalidTheme(format!("Failed to parse manifest.toml: {}", e))
        })?;

        // Extract theme names from [themes] section
        if let Some(themes_table) = manifest.get("themes").and_then(|v| v.as_table()) {
            for (theme_name, _variants) in themes_table {
                themes.push(theme_name.clone());
            }
        }

        // Sort themes alphabetically
        themes.sort();

        Ok(themes)
    }
}
